In [1]:
from pathlib import Path
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


ROOT_PROJECT = Path.cwd().parent
SRC = ROOT_PROJECT / 'src'
CHECKPOINT = ROOT_PROJECT / 'Data' / 'checkpoints'

if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from utils.analyze import (
    get_sizes_groups,
    describe_clusters,
    describe_clusters_median
)

KMeansRoute = CHECKPOINT / 'vercel_historic' / 'Kmeans'
KMeansDrainLogs = CHECKPOINT / 'drain_logs' / 'Kmeans_ver2'

In [2]:
X = pd.read_parquet(str(KMeansRoute))
##X_drains = pd.read_parquet(str(KMeansDrainLogs))

In [3]:
sizes_drains = get_sizes_groups(X)
sizes_drains

   labels  tamano  porcentajes
0       0   10299     0.084547
1       1   83815     0.688057
2       2   25750     0.211388
3       3    1950     0.016008

In [4]:
X_groups = get_sizes_groups(X)
X_groups

   labels  tamano  porcentajes
0       0   10299     0.084547
1       1   83815     0.688057
2       2   25750     0.211388
3       3    1950     0.016008

In [5]:
X_describe_clusters = describe_clusters(X)
#X_describe_clusters_drains = describe_clusters(X_drains)

In [6]:
X_describe_clusters

labels                                   0     1          2          3
routes_visited                        6.15  1.01       2.25      38.69
unique_routes                         5.99  1.00       2.18      38.56
activity_window_ms               300589.49  0.16  134967.30  406155.29
mean_time_between_requests_ms     65757.71  0.15  109858.78   14296.30
median_time_between_requests_ms   49626.56  0.15  109640.80    7248.09
is_one_shot                           0.00  1.00       0.00       0.00

## Revisar

In [8]:
X_describe_clusters_drains.to_json()

'{"0":{"conteo_requests":1.43,"times_timestamp":1.43,"request_amount":1.43,"routes_visited":1.43,"activity_window_ms":0.01,"mean_time_between_requests_ms":0.01,"median_time_between_requests_ms":0.01,"is_one_shot":0.64},"1":{"conteo_requests":5.09,"times_timestamp":5.09,"request_amount":5.09,"routes_visited":5.09,"activity_window_ms":21786647.7899999991,"mean_time_between_requests_ms":6608003.9000000004,"median_time_between_requests_ms":6608003.9000000004,"is_one_shot":0.0},"2":{"conteo_requests":3.95,"times_timestamp":3.95,"request_amount":3.95,"routes_visited":3.95,"activity_window_ms":1908972.99,"mean_time_between_requests_ms":834.9,"median_time_between_requests_ms":834.9,"is_one_shot":0.0},"3":{"conteo_requests":288.9,"times_timestamp":288.9,"request_amount":288.9,"routes_visited":288.9,"activity_window_ms":35620190.7100000009,"mean_time_between_requests_ms":89374.6,"median_time_between_requests_ms":89374.6,"is_one_shot":0.0}}'

In [9]:
median_drains = describe_clusters_median(X_drains)
median_drains

labels                             0           1       2           3
conteo_requests                  1.0         4.0     4.0        41.0
times_timestamp                  1.0         4.0     4.0        41.0
request_amount                   1.0         4.0     4.0        41.0
routes_visited                   1.0         4.0     4.0        41.0
activity_window_ms               0.0  15775003.0  1030.0  41412601.0
mean_time_between_requests_ms    0.0   1751391.0   378.0      2184.5
median_time_between_requests_ms  0.0   1751391.0   378.0      2184.5
is_one_shot                      1.0         0.0     0.0         0.0

In [10]:
median_drains.to_json()

'{"0":{"conteo_requests":1.0,"times_timestamp":1.0,"request_amount":1.0,"routes_visited":1.0,"activity_window_ms":0.0,"mean_time_between_requests_ms":0.0,"median_time_between_requests_ms":0.0,"is_one_shot":1.0},"1":{"conteo_requests":4.0,"times_timestamp":4.0,"request_amount":4.0,"routes_visited":4.0,"activity_window_ms":15775003.0,"mean_time_between_requests_ms":1751391.0,"median_time_between_requests_ms":1751391.0,"is_one_shot":0.0},"2":{"conteo_requests":4.0,"times_timestamp":4.0,"request_amount":4.0,"routes_visited":4.0,"activity_window_ms":1030.0,"mean_time_between_requests_ms":378.0,"median_time_between_requests_ms":378.0,"is_one_shot":0.0},"3":{"conteo_requests":41.0,"times_timestamp":41.0,"request_amount":41.0,"routes_visited":41.0,"activity_window_ms":41412601.0,"mean_time_between_requests_ms":2184.5,"median_time_between_requests_ms":2184.5,"is_one_shot":0.0}}'

In [12]:
view_drains = X_drains[X_drains['labels'] == 3]

view_drains = view_drains.sort_values(by = 'conteo_requests', ascending=True)
view_drains

,conteo_requests,times_timestamp,request_amount,routes_visited,activity_window_ms,mean_time_between_requests_ms,median_time_between_requests_ms,is_one_shot,ja4Digest,proxy.userAgent,proxy.clientIp,labels
5549,14,14,14,14,622727,2983.0,2983.0,False,t13d2212h2_231e334592e8_36bf25f296df,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...",52.167.144.147,3
5472,15,15,15,15,561484,3288.5,3288.5,False,t13d2212h2_231e334592e8_36bf25f296df,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...",157.55.39.15,3
5528,15,15,15,15,70763,477.5,477.5,False,t13d2212h2_231e334592e8_36bf25f296df,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...",40.77.167.27,3
5537,15,15,15,15,633131,8576.0,8576.0,False,t13d2212h2_231e334592e8_36bf25f296df,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...",40.77.167.42,3
5546,15,15,15,15,356611,2011.5,2011.5,False,t13d2212h2_231e334592e8_36bf25f296df,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...",40.77.167.72,3
...,...,...,...,...,...,...,...,...,...,...,...,...
5102,1506,1506,1506,1506,64478526,3056.0,3056.0,False,t13d181300_e8a523a41297_43ade6aba3df,Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...,66.249.79.229,3
5099,2092,2092,2092,2092,63060012,3132.0,3132.0,False,t13d181300_e8a523a41297_43ade6aba3df,Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bu...,66.249.79.226,3
87,5694,5694,5694,5694,64551716,10288.0,10288.0,False,t13d1011h2_61a7ad8aa9b6_3fcd1a44f3e3,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...",74.7.227.187,3
86,9076,9076,9076,9076,1737820,91.0,91.0,False,t13d1011h2_61a7ad8aa9b6_3fcd1a44f3e3,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...",216.73.217.34,3
85,41357,41357,41357,41357,10872273,89.0,89.0,False,t13d1011h2_61a7ad8aa9b6_3fcd1a44f3e3,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Ge...",216.73.216.150,3

In [17]:
view_drains['proxy.userAgent'].to_list()

['Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:151.0) Gecko/20100101 Firefox/151.0',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
 'CriteoBot/0.1 (+https://www.criteo.com/criteo-crawler/)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.4 Mobile/15E148 Safari/604.1',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.2 Mobile/15E148 Safari/604.1',
 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.7778.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'peer39_crawler/1.0',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'CriteoBot/0.1 (+https://www.criteo.com/criteo-crawler/)',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mediapartners-Google',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.66 Mobile Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36',
 'ias-va/3.3 (former https://www.admantx.com + https://integralads.com/about-ias/)',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 26_5_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/148.0.7778.166 Mobile/15E148 Safari/604.1',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; PerplexityBot/1.0; +https://perplexity.ai/perplexitybot)',
 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; PerplexityBot/1.0; +https://perplexity.ai/perplexitybot)',
 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
 'CriteoBot/0.1 (+https://www.criteo.com/criteo-crawler/)',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; PerplexityBot/1.0; +https://perplexity.ai/perplexitybot)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.5 Mobile/15E148 Safari/604.1',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'ias-va/3.3 (former https://www.admantx.com + https://integralads.com/about-ias/)',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.66 Mobile Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
 'ias-or/3.3 (former https://www.admantx.com + https://integralads.com/about-ias/)',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
 'Mediapartners-Google',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.4 Mobile/15E148 Safari/604.1',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; PerplexityBot/1.0; +https://perplexity.ai/perplexitybot)',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; PerplexityBot/1.0; +https://perplexity.ai/perplexitybot)',
 'CriteoBot/0.1 (+https://www.criteo.com/criteo-crawler/)',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
 'ias-va/3.3 (former https://www.admantx.com + https://integralads.com/about-ias/)',
 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36',
 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
 'CriteoBot/0.1 (+https://www.criteo.com/criteo-crawler/)',
 'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.66 Mobile Safari/537.36',
 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mediapartners-Google',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; PerplexityBot/1.0; +https://perplexity.ai/perplexitybot)',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)',
 'Mozilla/5.0 (compatible; DotBot/1.2; +https://opensiteexplorer.org/dotbot; help@moz.com)',

In [37]:
view_drains.sort_values(by = 'conteo_requests', ascending=True).head(50).to_json()

'{"conteo_requests":{"5549":14,"5472":15,"5528":15,"5537":15,"5546":15,"5376":15,"5677":15,"5559":15,"5644":15,"5565":15,"5575":15,"4802":15,"5582":15,"5513":16,"4804":16,"5652":16,"3619":16,"5555":16,"5391":16,"5643":16,"5641":17,"5387":17,"5447":17,"5432":17,"5516":17,"5403":17,"5121":17,"6633":17,"5374":17,"5690":18,"5615":18,"6624":18,"5519":18,"3786":18,"5414":18,"5478":18,"30":18,"5390":18,"4807":18,"5106":18,"5170":18,"5197":18,"5125":19,"5680":19,"5087":19,"3644":19,"5419":19,"5653":19,"6641":20,"4999":20},"times_timestamp":{"5549":14,"5472":15,"5528":15,"5537":15,"5546":15,"5376":15,"5677":15,"5559":15,"5644":15,"5565":15,"5575":15,"4802":15,"5582":15,"5513":16,"4804":16,"5652":16,"3619":16,"5555":16,"5391":16,"5643":16,"5641":17,"5387":17,"5447":17,"5432":17,"5516":17,"5403":17,"5121":17,"6633":17,"5374":17,"5690":18,"5615":18,"6624":18,"5519":18,"3786":18,"5414":18,"5478":18,"30":18,"5390":18,"4807":18,"5106":18,"5170":18,"5197":18,"5125":19,"5680":19,"5087":19,"3644":19,"5419":19,"5653":19,"6641":20,"4999":20},"request_amount":{"5549":14,"5472":15,"5528":15,"5537":15,"5546":15,"5376":15,"5677":15,"5559":15,"5644":15,"5565":15,"5575":15,"4802":15,"5582":15,"5513":16,"4804":16,"5652":16,"3619":16,"5555":16,"5391":16,"5643":16,"5641":17,"5387":17,"5447":17,"5432":17,"5516":17,"5403":17,"5121":17,"6633":17,"5374":17,"5690":18,"5615":18,"6624":18,"5519":18,"3786":18,"5414":18,"5478":18,"30":18,"5390":18,"4807":18,"5106":18,"5170":18,"5197":18,"5125":19,"5680":19,"5087":19,"3644":19,"5419":19,"5653":19,"6641":20,"4999":20},"routes_visited":{"5549":14,"5472":15,"5528":15,"5537":15,"5546":15,"5376":15,"5677":15,"5559":15,"5644":15,"5565":15,"5575":15,"4802":15,"5582":15,"5513":16,"4804":16,"5652":16,"3619":16,"5555":16,"5391":16,"5643":16,"5641":17,"5387":17,"5447":17,"5432":17,"5516":17,"5403":17,"5121":17,"6633":17,"5374":17,"5690":18,"5615":18,"6624":18,"5519":18,"3786":18,"5414":18,"5478":18,"30":18,"5390":18,"4807":18,"5106":18,"5170":18,"5197":18,"5125":19,"5680":19,"5087":19,"3644":19,"5419":19,"5653":19,"6641":20,"4999":20},"activity_window_ms":{"5549":622727,"5472":561484,"5528":70763,"5537":633131,"5546":356611,"5376":541604,"5677":38204,"5559":5194408,"5644":20779001,"5565":209738,"5575":424214,"4802":243128,"5582":17060176,"5513":24234861,"4804":23878184,"5652":56745534,"3619":23723321,"5555":24925683,"5391":490802,"5643":17437572,"5641":145545,"5387":49493480,"5447":403368,"5432":15929344,"5516":399049,"5403":49548174,"5121":55528814,"6633":64082472,"5374":20314829,"5690":130484,"5615":24223,"6624":61520704,"5519":32782467,"3786":62551745,"5414":29730333,"5478":15735376,"30":18012451,"5390":3005466,"4807":61432243,"5106":14869011,"5170":179999,"5197":53989,"5125":59840533,"5680":316394,"5087":50685287,"3644":59680405,"5419":628370,"5653":162206,"6641":57627701,"4999":1022306},"mean_time_between_requests_ms":{"5549":2983.0,"5472":3288.5,"5528":477.5,"5537":8576.0,"5546":2011.5,"5376":10173.0,"5677":2011.0,"5559":2525.5,"5644":1012.5,"5565":807.0,"5575":865.5,"4802":621.0,"5582":891.5,"5513":2718.0,"4804":192.0,"5652":1016.0,"3619":0.0,"5555":2009.0,"5391":20108.0,"5643":2047.0,"5641":1058.0,"5387":40105.0,"5447":0.0,"5432":19953.5,"5516":1955.0,"5403":157142.0,"5121":98527.5,"6633":253556.5,"5374":75601.0,"5690":0.0,"5615":0.0,"6624":936192.0,"5519":1998.0,"3786":841065.0,"5414":2362.0,"5478":2161.0,"30":317558.0,"5390":222.0,"4807":241.0,"5106":0.0,"5170":0.0,"5197":0.0,"5125":124829.0,"5680":2524.5,"5087":12385.0,"3644":412835.0,"5419":54.0,"5653":2035.0,"6641":283987.0,"4999":11885.0},"median_time_between_requests_ms":{"5549":2983.0,"5472":3288.5,"5528":477.5,"5537":8576.0,"5546":2011.5,"5376":10173.0,"5677":2011.0,"5559":2525.5,"5644":1012.5,"5565":807.0,"5575":865.5,"4802":621.0,"5582":891.5,"5513":2718.0,"4804":192.0,"5652":1016.0,"3619":0.0,"5555":2009.0,"5391":20108.0,"5643":2047.0,"5641":1058.0,"5387":40105.0,"5447":0.0,"5432":19953.5,"5516":1955.0,"5403":157142.0,"5121":98527.5,"6633":253556.5,"5374":75601.0,"5690":0.0,"5615":0.0,"6624":936192.0,"5519":1998.0,"3786":841065.0,"5414":2362.0,"5478":2161.0,"30":317558.0,"5390":222.0,"4807":241.0,"5106":0.0,"5170":0.0,"5197":0.0,"5125":124829.0,"5680":2524.5,"5087":12385.0,"3644":412835.0,"5419":54.0,"5653":2035.0,"6641":283987.0,"4999":11885.0},"is_one_shot":{"5549":false,"5472":false,"5528":false,"5537":false,"5546":false,"5376":false,"5677":false,"5559":false,"5644":false,"5565":false,"5575":false,"4802":false,"5582":false,"5513":false,"4804":false,"5652":false,"3619":false,"5555":false,"5391":false,"5643":false,"5641":false,"5387":false,"5447":false,"5432":false,"5516":false,"5403":false,"5121":false,"6633":false,"5374":false,"5690":false,"5615":false,"6624":false,"5519":false,"3786":false,"5414":false,"5478":false,"30":false,"5390":false,"4807":false,"5106":false,"5170":false,"5197":false,"5125":false,"5680":false,"5087":false,"3644":false,"5419":false,"5653":false,"6641":false,"4999":false},"ja4Digest":{"5549":"t13d2212h2_231e334592e8_36bf25f296df","5472":"t13d2212h2_231e334592e8_36bf25f296df","5528":"t13d2212h2_231e334592e8_36bf25f296df","5537":"t13d2212h2_231e334592e8_36bf25f296df","5546":"t13d2212h2_231e334592e8_36bf25f296df","5376":"t13d2212h2_231e334592e8_36bf25f296df","5677":"t13d2213h2_231e334592e8_89322cc15493","5559":"t13d2212h2_231e334592e8_36bf25f296df","5644":"t13d2213h2_231e334592e8_89322cc15493","5565":"t13d2212h2_231e334592e8_36bf25f296df","5575":"t13d2212h2_231e334592e8_36bf25f296df","4802":"t13d1617h2_86a278354501_3cbfd9057e0d","5582":"t13d2213h2_231e334592e8_89322cc15493","5513":"t13d2212h2_231e334592e8_36bf25f296df","4804":"t13d1711h2_5b57614c22b0_5894756fee65","5652":"t13d2213h2_231e334592e8_89322cc15493","3619":"t13d1516h2_8daaf6152771_d8a2da3f94cd","5555":"t13d2212h2_231e334592e8_36bf25f296df","5391":"t13d2212h2_231e334592e8_36bf25f296df","5643":"t13d2213h2_231e334592e8_89322cc15493","5641":"t13d2213h2_231e334592e8_89322cc15493","5387":"t13d2212h2_231e334592e8_36bf25f296df","5447":"t13d2212h2_231e334592e8_36bf25f296df","5432":"t13d2212h2_231e334592e8_36bf25f296df","5516":"t13d2212h2_231e334592e8_36bf25f296df","5403":"t13d2212h2_231e334592e8_36bf25f296df","5121":"t13d181300_e8a523a41297_43ade6aba3df","6633":"t13d361100_018971650b2c_e8b3fe21f08b","5374":"t13d2212h2_231e334592e8_36bf25f296df","5690":"t13d260900_6d1bcf7a4624_188c7f576dcd","5615":"t13d2213h2_231e334592e8_89322cc15493","6624":"t13d361100_018971650b2c_e8b3fe21f08b","5519":"t13d2212h2_231e334592e8_36bf25f296df","3786":"t13d1516h2_8daaf6152771_d8a2da3f94cd","5414":"t13d2212h2_231e334592e8_36bf25f296df","5478":"t13d2212h2_231e334592e8_36bf25f296df","30":"t12d220400_80735a4ba246_352d62b41124","5390":"t13d2212h2_231e334592e8_36bf25f296df","4807":"t13d1711h2_5b57614c22b0_5894756fee65","5106":"t13d181300_e8a523a41297_43ade6aba3df","5170":"t13d2013h2_a09f3c656075_7f0f34a4126d","5197":"t13d2013h2_a09f3c656075_7f0f34a4126d","5125":"t13d181300_e8a523a41297_43ade6aba3df","5680":"t13d2213h2_231e334592e8_89322cc15493","5087":"t13d181300_e8a523a41297_43ade6aba3df","3644":"t13d1516h2_8daaf6152771_d8a2da3f94cd","5419":"t13d2212h2_231e334592e8_36bf25f296df","5653":"t13d2213h2_231e334592e8_89322cc15493","6641":"t13d371200_db35923f8641_7c76daad20ec","4999":"t13d1713h1_ab0a1bf427ad_8537cf56674e"},"proxy.userAgent":{"5549":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5472":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5528":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5537":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5546":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5376":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","5677":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5559":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5644":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5565":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5575":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","4802":"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64; rv:151.0) Gecko\\/20100101 Firefox\\/151.0","5582":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","5513":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","4804":"Mozilla\\/5.0 (X11; Linux x86_64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/136.0.0.0 Safari\\/537.36","5652":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","3619":"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Safari\\/537.36","5555":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5391":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","5643":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5641":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5387":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","5447":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","5432":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","5516":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5403":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","5121":"Mozilla\\/5.0 (compatible; Googlebot\\/2.1; +http:\\/\\/www.google.com\\/bot.html)","6633":"CriteoBot\\/0.1 (+https:\\/\\/www.criteo.com\\/criteo-crawler\\/)","5374":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","5690":"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Safari\\/537.36","5615":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","6624":"CriteoBot\\/0.1 (+https:\\/\\/www.criteo.com\\/criteo-crawler\\/)","5519":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","3786":"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Safari\\/537.36","5414":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","5478":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","30":"peer39_crawler\\/1.0","5390":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","4807":"Mozilla\\/5.0 (X11; Linux x86_64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/136.0.0.0 Safari\\/537.36","5106":"Mozilla\\/5.0 (Linux; Android 6.0.1; Nexus 5X Build\\/MMB29P) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.7778.96 Mobile Safari\\/537.36 (compatible; Googlebot\\/2.1; +http:\\/\\/www.google.com\\/bot.html)","5170":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/26.2 Mobile\\/15E148 Safari\\/604.1","5197":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/26.4 Mobile\\/15E148 Safari\\/604.1","5125":"Mozilla\\/5.0 (compatible; Googlebot\\/2.1; +http:\\/\\/www.google.com\\/bot.html)","5680":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","5087":"Mediapartners-Google","3644":"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Safari\\/537.36","5419":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit\\/537.51.1 (KHTML, like Gecko) Version\\/7.0 Mobile\\/11A465 Safari\\/9537.53 (compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm)","5653":"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; bingbot\\/2.0; +http:\\/\\/www.bing.com\\/bingbot.htm) Chrome\\/116.0.1938.76 Safari\\/537.36","6641":"ias-va\\/3.3 (former https:\\/\\/www.admantx.com + https:\\/\\/integralads.com\\/about-ias\\/)","4999":"Mozilla\\/5.0 (Linux; Android 14) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/119.0.6045.66 Mobile Safari\\/537.36"},"proxy.clientIp":{"5549":"52.167.144.147","5472":"157.55.39.15","5528":"40.77.167.27","5537":"40.77.167.42","5546":"40.77.167.72","5376":"157.55.39.14","5677":"52.167.144.158","5559":"52.167.144.18","5644":"207.46.13.126","5565":"52.167.144.19","5575":"52.167.144.221","4802":"206.223.234.91","5582":"157.55.39.197","5513":"207.46.13.6","4804":"136.119.129.236","5652":"207.46.13.7","3619":"143.105.17.86","5555":"52.167.144.167","5391":"157.55.39.54","5643":"207.46.13.125","5641":"207.46.13.116","5387":"157.55.39.49","5447":"52.167.144.159","5432":"40.77.167.38","5516":"207.46.13.86","5403":"207.46.13.127","5121":"66.249.79.224","6633":"74.119.118.49","5374":"157.55.39.10","5690":"136.226.112.84","5615":"52.167.144.204","6624":"74.119.118.198","5519":"40.77.167.121","3786":"193.186.4.213","5414":"207.46.13.63","5478":"157.55.39.200","30":"204.15.208.45","5390":"157.55.39.53","4807":"34.60.131.171","5106":"66.249.79.233","5170":"201.108.9.196","5197":"73.70.129.143","5125":"66.249.79.228","5680":"52.167.144.182","5087":"72.14.199.236","3644":"162.120.186.160","5419":"40.77.167.123","5653":"207.46.13.86","6641":"35.175.92.196","4999":"207.175.11.177"},"labels":{"5549":3,"5472":3,"5528":3,"5537":3,"5546":3,"5376":3,"5677":3,"5559":3,"5644":3,"5565":3,"5575":3,"4802":3,"5582":3,"5513":3,"4804":3,"5652":3,"3619":3,"5555":3,"5391":3,"5643":3,"5641":3,"5387":3,"5447":3,"5432":3,"5516":3,"5403":3,"5121":3,"6633":3,"5374":3,"5690":3,"5615":3,"6624":3,"5519":3,"3786":3,"5414":3,"5478":3,"30":3,"5390":3,"4807":3,"5106":3,"5170":3,"5197":3,"5125":3,"5680":3,"5087":3,"3644":3,"5419":3,"5653":3,"6641":3,"4999":3}}'

In [38]:
X_drains.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6755 entries, 0 to 6754
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   conteo_requests                  6755 non-null   int64
 1   times_timestamp                  6755 non-null   int64
 2   request_amount                   6755 non-null   int64
 3   routes_visited                   6755 non-null   int64
 4   activity_window_ms               6755 non-null   int64
 5   mean_time_between_requests_ms    6755 non-null   float64
 6   median_time_between_requests_ms  6755 non-null   float64
 7   is_one_shot                      6755 non-null   bool
 8   ja4Digest                        6755 non-null   object
 9   proxy.userAgent                  6755 non-null   object
 10  proxy.clientIp                   6755 non-null   object
 11  labels                           6755 non-null   int32
dtypes: bool(1), float64(2), int32(1), int64(5), object(3)
memory usage: 560.8+ KB

In [22]:
FRIENDLY_BOTS = {
    # Search engines
    "googlebot": [
        "googlebot",
    ],
    "bingbot": [
        "bingbot",
    ],

    # Google Ads / AdSense
    "mediapartners_google": [
        "mediapartners-google",
    ],

    # OpenAI / AI search you want to keep
    "gptbot": [
        "gptbot",
    ],
    "oai_searchbot": [
        "oai-searchbot",
        "openai.com/searchbot",
    ],

    # Ad partners / verification useful for ads ecosystem
    "criteobot": [
        "criteobot",
        "criteo-crawler",
    ],
    "ias": [
        "ias-va",
        "ias-or",
        "ias crawler",
        "ias_crawler",
        "integralads",
        "admantx",
    ],
}

agents = view_drains['proxy.userAgent'].unique()

In [49]:
view_stats = (
    view_drains
    .groupby(['proxy.userAgent'])
    .agg(
        conteo_routes_visitadas = ('routes_visited', 'sum')
    )
)

view_stats = view_stats.sort_values('conteo_routes_visitadas', ascending = False)

In [50]:
view_stats

                                                    conteo_routes_visitadas
proxy.userAgent
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gec...                    50433
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Bui...                     9716
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gec...                     5818
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gec...                     5694
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/...                     3528
Mozilla/5.0 (Windows NT 10.0; Win64; x64) Apple...                     1418
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)...                     1223
Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac...                     1107
Mozilla/5.0 (Windows NT 10.0; Win64; x64) Apple...                      577
Mediapartners-Google                                                    419
IAS Crawler (ias_crawler; http://integralads.co...                      350
ias-va/3.3 (former https://www.admantx.com + ht...                      315
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gec...                      151
Mozilla/5.0 (compatible; Googlebot/2.1; +http:/...                      116
CriteoBot/0.1 (+https://www.criteo.com/criteo-c...                      112
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537...                       85
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:15...                       81
Mozilla/5.0 (Linux; Android 14) AppleWebKit/537...                       73
Mozilla/5.0 (Windows NT 10.0; Win64; x64) Apple...                       63
Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...                       44
Mozilla/5.0 (compatible; DotBot/1.2; +https://o...                       42
ias-or/3.3 (former https://www.admantx.com + ht...                       25
Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...                       23
Mozilla/5.0 (iPhone; CPU iPhone OS 26_5_0 like ...                       21
Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Ma...                       18
peer39_crawler/1.0                                                       18

In [51]:


def detect_friendly_bot(user_agent, bot_patterns):

    ua = str(user_agent).lower()

    for bot_name, patterns in bot_patterns.items():

        for pattern in patterns:

            if pattern.lower() in ua:

                return bot_name

    return None

view_stats_labeled = view_stats.copy()

view_stats_labeled["friendly_bot_type"] = view_stats_labeled.index.map(

    lambda ua: detect_friendly_bot(ua, FRIENDLY_BOTS)

)

view_stats_labeled["is_friendly"] = view_stats_labeled["friendly_bot_type"].notna()

view_stats_labeled = view_stats_labeled.sort_values(

    "conteo_routes_visitadas",

    ascending=False

)

view_stats_labeled

,conteo_routes_visitadas,friendly_bot_type,is_friendly
proxy.userAgent,,,
"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; ClaudeBot/1.0; +claudebot@anthropic.com)",50433,None,False
"Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.7778.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",9716,googlebot,True
"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36",5818,bingbot,True
"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GPTBot/1.4; +https://openai.com/gptbot)",5694,gptbot,True
"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36",3528,None,False
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36",1418,None,False
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36; compatible; OAI-SearchBot/1.4; +https://openai.com/searchbot",1223,oai_searchbot,True
"Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)",1107,bingbot,True
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36",577,None,False
Mediapartners-Google,419,mediapartners_google,True
IAS Crawler (ias_crawler; http://integralads.com/site-indexing-policy/),350,ias,True
ias-va/3.3 (former https://www.admantx.com + https://integralads.com/about-ias/),315,ias,True
"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; PerplexityBot/1.0; +https://perplexity.ai/perplexitybot)",151,None,False
Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html),116,googlebot,True
CriteoBot/0.1 (+https://www.criteo.com/criteo-crawler/),112,criteobot,True
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",85,None,False
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:151.0) Gecko/20100101 Firefox/151.0,81,None,False
"Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.66 Mobile Safari/537.36",73,None,False
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0",63,None,False
"Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.4 Mobile/15E148 Safari/604.1",44,None,False
Mozilla/5.0 (compatible; DotBot/1.2; +https://opensiteexplorer.org/dotbot; help@moz.com),42,None,False
ias-or/3.3 (former https://www.admantx.com + https://integralads.com/about-ias/),25,ias,True
"Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.5 Mobile/15E148 Safari/604.1",23,None,False
"Mozilla/5.0 (iPhone; CPU iPhone OS 26_5_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/148.0.7778.166 Mobile/15E148 Safari/604.1",21,None,False
"Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.2 Mobile/15E148 Safari/604.1",18,None,False
peer39_crawler/1.0,18,None,False

In [52]:
view_stats_labeled[view_stats_labeled['is_friendly'] == False]

,conteo_routes_visitadas,friendly_bot_type,is_friendly
proxy.userAgent,,,
"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; ClaudeBot/1.0; +claudebot@anthropic.com)",50433,None,False
"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Mobile Safari/537.36",3528,None,False
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36",1418,None,False
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.6943.141 Safari/537.36",577,None,False
"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; PerplexityBot/1.0; +https://perplexity.ai/perplexitybot)",151,None,False
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",85,None,False
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:151.0) Gecko/20100101 Firefox/151.0,81,None,False
"Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.66 Mobile Safari/537.36",73,None,False
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0",63,None,False
"Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.4 Mobile/15E148 Safari/604.1",44,None,False
Mozilla/5.0 (compatible; DotBot/1.2; +https://opensiteexplorer.org/dotbot; help@moz.com),42,None,False
"Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.5 Mobile/15E148 Safari/604.1",23,None,False
"Mozilla/5.0 (iPhone; CPU iPhone OS 26_5_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/148.0.7778.166 Mobile/15E148 Safari/604.1",21,None,False
"Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.2 Mobile/15E148 Safari/604.1",18,None,False
peer39_crawler/1.0,18,None,False

In [53]:
view_stats_labeled[view_stats_labeled['is_friendly'] == False].to_json()

'{"conteo_routes_visitadas":{"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; ClaudeBot\\/1.0; +claudebot@anthropic.com)":50433,"Mozilla\\/5.0 (Linux; Android 10; K) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Mobile Safari\\/537.36":3528,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Safari\\/537.36":1418,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/133.0.6943.141 Safari\\/537.36":577,"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; PerplexityBot\\/1.0; +https:\\/\\/perplexity.ai\\/perplexitybot)":151,"Mozilla\\/5.0 (X11; Linux x86_64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/136.0.0.0 Safari\\/537.36":85,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64; rv:151.0) Gecko\\/20100101 Firefox\\/151.0":81,"Mozilla\\/5.0 (Linux; Android 14) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/119.0.6045.66 Mobile Safari\\/537.36":73,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Safari\\/537.36 Edg\\/148.0.0.0":63,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/26.4 Mobile\\/15E148 Safari\\/604.1":44,"Mozilla\\/5.0 (compatible; DotBot\\/1.2; +https:\\/\\/opensiteexplorer.org\\/dotbot; help@moz.com)":42,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/26.5 Mobile\\/15E148 Safari\\/604.1":23,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 26_5_0 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) CriOS\\/148.0.7778.166 Mobile\\/15E148 Safari\\/604.1":21,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/26.2 Mobile\\/15E148 Safari\\/604.1":18,"peer39_crawler\\/1.0":18},"friendly_bot_type":{"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; ClaudeBot\\/1.0; +claudebot@anthropic.com)":null,"Mozilla\\/5.0 (Linux; Android 10; K) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Mobile Safari\\/537.36":null,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Safari\\/537.36":null,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/133.0.6943.141 Safari\\/537.36":null,"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; PerplexityBot\\/1.0; +https:\\/\\/perplexity.ai\\/perplexitybot)":null,"Mozilla\\/5.0 (X11; Linux x86_64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/136.0.0.0 Safari\\/537.36":null,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64; rv:151.0) Gecko\\/20100101 Firefox\\/151.0":null,"Mozilla\\/5.0 (Linux; Android 14) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/119.0.6045.66 Mobile Safari\\/537.36":null,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Safari\\/537.36 Edg\\/148.0.0.0":null,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/26.4 Mobile\\/15E148 Safari\\/604.1":null,"Mozilla\\/5.0 (compatible; DotBot\\/1.2; +https:\\/\\/opensiteexplorer.org\\/dotbot; help@moz.com)":null,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/26.5 Mobile\\/15E148 Safari\\/604.1":null,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 26_5_0 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) CriOS\\/148.0.7778.166 Mobile\\/15E148 Safari\\/604.1":null,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/26.2 Mobile\\/15E148 Safari\\/604.1":null,"peer39_crawler\\/1.0":null},"is_friendly":{"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; ClaudeBot\\/1.0; +claudebot@anthropic.com)":false,"Mozilla\\/5.0 (Linux; Android 10; K) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Mobile Safari\\/537.36":false,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Safari\\/537.36":false,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/133.0.6943.141 Safari\\/537.36":false,"Mozilla\\/5.0 AppleWebKit\\/537.36 (KHTML, like Gecko; compatible; PerplexityBot\\/1.0; +https:\\/\\/perplexity.ai\\/perplexitybot)":false,"Mozilla\\/5.0 (X11; Linux x86_64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/136.0.0.0 Safari\\/537.36":false,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64; rv:151.0) Gecko\\/20100101 Firefox\\/151.0":false,"Mozilla\\/5.0 (Linux; Android 14) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/119.0.6045.66 Mobile Safari\\/537.36":false,"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/148.0.0.0 Safari\\/537.36 Edg\\/148.0.0.0":false,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/26.4 Mobile\\/15E148 Safari\\/604.1":false,"Mozilla\\/5.0 (compatible; DotBot\\/1.2; +https:\\/\\/opensiteexplorer.org\\/dotbot; help@moz.com)":false,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/26.5 Mobile\\/15E148 Safari\\/604.1":false,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 26_5_0 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) CriOS\\/148.0.7778.166 Mobile\\/15E148 Safari\\/604.1":false,"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/26.2 Mobile\\/15E148 Safari\\/604.1":false,"peer39_crawler\\/1.0":false}}'